### ISSUE TITLE
Optimization - Snaking Draft Algorithm

### ISSUE THREAD

**Issue by dbodenschatz** [jared-schmidt/ps-volleyball#18]
The optimization would be nice if we could implement a snaking draft player that would start with the highest rated player and snake its way down.

**Comment by jared-schmidt** [comment]
not sure what you mean? Just have it sort the player by win% then go down the list? (this is the way it used to be)

**Comment by dbodenschatz** [comment]
Here is the concept behind the snake draft @jared-schmidt 

![snakedraft](https://cloud.githubusercontent.com/assets/13000293/15223256/77e1d6a2-1841-11e6-87b4-9ea7e57764fa.jpg)
